# Generated by Django 4.1.7 on 2024-01-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_creado_en_products_create_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
